# Generated by Django 3.0.4 on 2020-04-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_article_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_id', models.CharField(max_length=30)),
                ('public_access_key', models.CharField(max_length=35)),
                ('username', models.CharField(max_length=20)),
                ('points', models.CharField(max_length=20)),
            ],
        ),
    ]
