# Generated by Django 3.0.4 on 2020-04-10 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='article',
        ),
    ]
