# Generated by Django 3.0.4 on 2020-04-11 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_delete_article'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='db_id',
        ),
    ]
