# Generated by Django 3.0.4 on 2020-04-11 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_remove_user_db_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='g_id',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='spotify_ref',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AddField(
            model_name='user',
            name='spotify_sec',
            field=models.CharField(default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='user',
            name='points',
            field=models.CharField(default='0', max_length=8),
        ),
        migrations.AlterField(
            model_name='user',
            name='public_access_key',
            field=models.CharField(default='0', max_length=35),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='null', max_length=20),
        ),
    ]
