# Generated by Django 3.0.4 on 2020-04-13 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20200411_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='g_id',
            field=models.CharField(default='0', max_length=100, primary_key='true', serialize=False),
        ),
    ]
