# Generated by Django 3.0.4 on 2020-04-13 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20200413_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='spotify_ref',
        ),
        migrations.RemoveField(
            model_name='user',
            name='spotify_sec',
        ),
    ]
